
title: 炸了的米花的博客
description: 欢迎来到炸了的米花的个人博客！
baseurl: "" # the subpath of your site, e.g. /blog
url: "popcornboom.github.io"

# Author
author-name:    POPCORNBOOM
author-image:   1.jpg
author-job:     开发 创客 网管 FAE
author-email:   popcornboom_137@qq.com
author-twitter:  PopcornBoom137
about-author:   17岁，学生。点击上方头像查看我的详细信息。

# Social settings
social-twitter:   PopcornBoom137
social-facebook:
social-github:    POPCORNBOOM
social-pinterest: 
social-instagram: 
social-youtube:
social-vk:   
social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: POPCORNBOOM # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

